import { useState } from 'react'

const reports = [
  {
    personnel_id: 'pcpl-001',
    officer: 'Mon Maguas',
    date_time: '2026-04-09T09:15:00',
    assigned_area: 'Cabagan Public Market Zone',
    report_type: 'incident',
    title: 'Minor Traffic Accident',
    description: 'A minor two-vehicle collision was recorded near the market entrance. No casualties were reported and traffic flow was normalized after initial response.',
    location: 'Near Cabagan Public Market Main Gate',
  },
  {
    personnel_id: 'psms-002',
    officer: 'GerryBoy Aggabao',
    date_time: '2026-04-09T10:45:00',
    assigned_area: 'Municipal Hall Perimeter',
    report_type: 'checkpoint',
    title: 'Vehicle Inspection Checkpoint',
    description: 'Routine checkpoint operations were completed and standard document checks were conducted for passing motorists.',
    location: 'Municipal Hall Front Checkpoint',
  },
  {
    personnel_id: 'pltc-003',
    officer: 'Romel Manzano',
    date_time: '2026-04-09T11:30:00',
    assigned_area: 'Barangay Centro Route',
    report_type: 'patrol',
    title: 'Public Visibility Patrol',
    description: 'Foot and mobile patrols were conducted around business zones and school vicinity to maintain visibility and deter petty incidents.',
    location: 'Barangay Centro Covered Court Vicinity',
  },
  {
    personnel_id: 'pcpl-001',
    officer: 'Mon Maguas',
    date_time: '2026-04-08T22:20:00',
    assigned_area: 'Highway Checkpoint North',
    report_type: 'backup',
    title: 'Backup Request During Disturbance',
    description: 'Backup assistance was requested for crowd control after a roadside disturbance. Situation was resolved without escalation.',
    location: 'Maharlika Highway North, KM 412 Checkpoint',
  },
  {
    personnel_id: 'psms-002',
    officer: 'GerryBoy Aggabao',
    date_time: '2026-04-08T19:10:00',
    assigned_area: 'School Safety Patrol Route',
    report_type: 'others',
    title: 'Community Coordination Update',
    description: 'Coordinated with barangay officials regarding evening traffic rerouting and safety reminders for parents and students.',
    location: 'San Juan Access Road Near School Zone',
  },
]

const formatDateTime = (isoValue) => {
  if (!isoValue) {
    return '-'
  }

  return new Intl.DateTimeFormat('en-PH', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  }).format(new Date(isoValue))
}

const toCsvValue = (value) => `"${String(value ?? '').replace(/"/g, '""')}"`

function ReportsPage() {
  const [reportMessage, setReportMessage] = useState('')

  const handleGenerateReport = () => {
    const generatedAtIso = new Date().toISOString()

    const csvRows = [
      ['Generated At', formatDateTime(generatedAtIso)],
      ['Generated By', 'Supervisor'],
      [],
      ['Police Reports'],
      ['personnel_id', 'officer', 'date_time', 'assigned_area', 'report_type', 'title', 'description', 'location'],
      ...reports.map((report) => [
        report.personnel_id,
        report.officer,
        report.date_time,
        report.assigned_area,
        report.report_type,
        report.title,
        report.description,
        report.location,
      ]),
    ]

    const csvContent = csvRows
      .map((row) => (row.length === 0 ? '' : row.map(toCsvValue).join(',')))
      .join('\n')

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
    const url = URL.createObjectURL(blob)
    const downloadAnchor = document.createElement('a')
    const fileStamp = generatedAtIso.replace(/[-:TZ]/g, '').slice(0, 14)

    downloadAnchor.href = url
    downloadAnchor.download = `bantaycabagan-report-${fileStamp}.csv`
    document.body.appendChild(downloadAnchor)
    downloadAnchor.click()
    document.body.removeChild(downloadAnchor)
    URL.revokeObjectURL(url)

    setReportMessage('Report generated and downloaded successfully.')
  }

  return (
    <div className="page-container fade-in p-3 p-md-4">
      <div className="page-header mb-4 reports-header">
        <div>
          <h2 className="page-title mb-0 fw-bold">Reports</h2>
          <p className="page-subtitle text-body-secondary mb-0">Police incident and patrol report records</p>
        </div>
        <button type="button" className="report-generate-btn" onClick={handleGenerateReport}>
          Generate Report
        </button>
      </div>

      {reportMessage && <small className="report-feedback d-block mb-3">{reportMessage}</small>}

      <div className="widget-card slide-up p-3 overflow-auto no-scrollbar">
        <h3 className="widget-title mb-3">Police Reports</h3>

        <table className="personnel-table table align-middle mb-0">
          <thead>
            <tr>
              <th>personnel_id</th>
              <th>officer</th>
              <th>date_time</th>
              <th>assigned_area</th>
              <th>report_type</th>
              <th>title</th>
              <th>description</th>
              <th>location</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((report) => (
              <tr key={`${report.personnel_id}-${report.date_time}`} className="personnel-row">
                <td>{report.personnel_id}</td>
                <td>{report.officer}</td>
                <td>{formatDateTime(report.date_time)}</td>
                <td>{report.assigned_area}</td>
                <td>{report.report_type}</td>
                <td>{report.title}</td>
                <td>{report.description}</td>
                <td>{report.location}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

export default ReportsPage
